version: "3"
services:
  mysql:
    image: mysql
    restart: always
    ports:
      - 3315:3306
    volumes:
      - '/Users/iman/Documents/volumes/iman/mysql:/var/lib/mysql'
    environment:
      MYSQL_ROOT_PASSWORD: Iman.3802
    networks:
      - i2

networks:
  i2:
    driver: bridge
